### ISSUE TITLE
EC2 instance doesn't inherit groups if launched with spot event plugin json template

### ISSUE THREAD

**Issue by queglay** [ThinkboxSoftware/Deadline#49]
currently when I use this with the spot fleet plugin, the groups don't seem to pickup from the json definition of the spot fleet / the tags for the deadlinegroup on the ec2 instance.

It would be great if this plugin was able to determine if it is running as an ec2 instance VS running out of AWS and query the tags for the groups it is meant to inherit in the event that it is an EC2 instance.

**Comment by RandomInsano** [comment]
Great idea! This should work these days as long as you've got the right instance role applied. Details here:
https://docs.thinkboxsoftware.com/products/deadline/10.2/1_User%20Manual/manual/event-spot-permissions.html#event-spot-fleet-role-ref-label

If that doesn't work as expected, please dig around in the forums or cut us a ticket. As usual, you can find how to get to us from https://awsthinkbox.com/support
