### ISSUE TITLE
Deadline installation corrupt from version 10.1.13.2 when dbauth=true with user and password

### ISSUE THREAD

**Issue by antars-es** [ThinkboxSoftware/Deadline#50]
Before 10.1.13.2 version (being the last one 100% tested by us 10.1.9.2), the installation of a new repository with the flags --dbauth true --dbuser <DB Username> --dbpassword <DB password> worked correctly. Since that version, the same install script does not work. The repository installs, but neither the deadline workers nor the deadline pulse can connect to it afterwards. Their logs state that "db auth has been configured, but no password has been provided". When checking the "connection.ini" file in the settings folder of the Deadline Repository, both the fields "Username" and "PasswordHash" are empty! It seems the installer is not filling in those fields properly when installation is finished. This problem does not happen if updating an existing 10.1.9.1 into a newer version, as the connection.ini is kept during the installation.
So, summarizing:
- In a mongo db setup with user/password enabled in the database, if deadline repository (10.1.13.2+) is installed over an existing (previous) installation, it works properly
- In the same setup (mongo with auth enabled database), if the deadline repository is configured in a clean directory, the connection.ini does not get filled with the proper auth parameters, and then no one can connect to deadline. As there is no way to reconfigure the database connection, a full install in a previous version is needed to recover the password hash.

Install script should be reviewed so that connection.ini is properly filled in a clean install.

**Comment by RandomInsano** [comment]
I *think* we fixed this in 10.1.21.4 and forgot to tell you 😅

> * Fixed a Repository installation failure that can occur when upgrading from Deadline 10.1.9 or earlier if authentication is enabled on the database and the certificate is password protected.
> * Fixed an issue in the Repository installer that could prevent it from connecting to an existing database with user authentication enabled.
> https://docs.thinkboxsoftware.com/products/deadline/10.2/1_User%20Manual/manual/release-notes.html#deadline-10-1-21-4

Sorry about missing this for awhile. I'm going to close this one out and if it's still a problem please re-open! This one may be a better candidate for the forums or zendesk though. Details on how to reach out here:
https://awsthinkbox.com/support
