### ISSUE TITLE
Authenticated WebService (REST API) not working in 10.1.20.3

### ISSUE THREAD

**Issue by antars-es** [ThinkboxSoftware/Deadline#51]
When we configure the webservice as did in previous versions (default install but port changed to 8082), it works properly whenever user authentication is NOT enabled (Deadline Web Service 10.1 [v10.1.20.3 Release (1a0d97d0f)] is shown). However, when we enable "require authentication" under repository options and reboot the webservice, we always get a 401 unauthorized, and no prompt for user/password is shown, even if a deadline user with a password exist in the system. This behavior might happen since previous versions.

**Comment by RandomInsano** [comment]
I did some testing here and I'm seeing a 405 not allowed from my Mac:

```
$ curl -I http://localhost:8081/api/jobs?JobID=63e131868c7a5f1f51a8ba15 -u "me"
Enter host password for user 'me':
HTTP/1.1 405 Method Not Allowed
Date: Fri, 28 Jul 2023 22:47:10 GMT
Server: Kestrel
Allow: DELETE, GET, OPTIONS, POST, PUT
```

I think this will better be served by the team by cutting us a ticket at https://awsthinkbox.com/support or the forums at https://forums.thinkboxsoftware.com.

I did some quick checks for you already in our tickets and I didn't find anything specific yet, so it'll be worth working with someone through on official support channel.
