### ISSUE TITLE
Plugin: SampleSimplePlugin link broken in Readme.txt

### ISSUE THREAD

**Issue by johhnry** [ThinkboxSoftware/Deadline#53]
Hi,

This link is broken and points to a `404` page in the documentation:

https://github.com/ThinkboxSoftware/Deadline/blob/15c583b215cc1658458e261d267c5800402321b1/Custom/plugins/SampleSimplePlugin/Readme.txt#L23

Redirected to -> https://www.awsthinkbox.com/products/deadline/6.2/1_user%20manual/index.html

**Comment by anthonygelatka** [comment]
they're all broken links, for some reason they pulled all the old versions. It usually requires renaming the number from whatever (6.2) to the latest version (10.1)

I just tested that and it doesn't work, but the link below does. Be wary a lot of this github stuff is ancient
https://docs.thinkboxsoftware.com/products/deadline/10.1/1_User%20Manual/index.html

**Comment by johhnry** [comment]
Hi @anthonygelatka,

Thanks for the quick answer, you are right the latest updates are quite old on this repo  so maybe the issue wasn't necessary ;)
